import { ClockIcon, MailIcon, MapPinIcon, PhoneIcon, WhatsAppIcon } from "@/lib/icons";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/site/section-heading";
import { business } from "@/config/business";
import { waGeneralMessage, waLink } from "@/lib/whatsapp";

export function ContactLocation() {
  return <section id="lokasi" className="bg-[#FAFAF8] py-16 md:py-20"><div className="mx-auto max-w-6xl px-4"><div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-start"><div><SectionHeading eyebrow="Lokasi & kontak" title="Temukan kami dan hubungi tim kami" description="Datang langsung atau kirim lokasi kendaraan Anda. Tim kami siap membantu kebutuhan aki mobil, motor, dan kendaraan listrik." /><div className="mt-7 overflow-hidden rounded-2xl bg-white p-2 shadow-sm ring-1 ring-brand-dark/5"><div className="aspect-[16/10] overflow-hidden rounded-xl bg-muted"><iframe src={business.googleMapsEmbed} title={`Lokasi ${business.name} di ${business.city}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen className="h-full w-full border-0" /></div></div></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-brand-dark/5 md:p-8"><h3 className="text-xl font-black tracking-tight">Kontak {business.name}</h3><ul className="mt-6 flex flex-col gap-5 text-sm"><li className="flex items-start gap-3"><MapPinIcon className="mt-0.5 size-5 shrink-0 text-brand-red" /><a href={business.googleMapsUrl} target="_blank" rel="noopener noreferrer" className="leading-relaxed text-muted-foreground hover:text-brand-red"><span className="block font-bold text-foreground">{business.addressShort}</span>{business.address}</a></li><li className="flex items-start gap-3"><WhatsAppIcon className="mt-0.5 size-5 shrink-0 text-brand-red" /><a href={waLink(waGeneralMessage())} target="_blank" rel="noopener noreferrer" className="font-bold hover:text-brand-red">WhatsApp {business.phoneDisplay}</a></li><li className="flex items-start gap-3"><PhoneIcon className="mt-0.5 size-5 shrink-0 text-brand-red" /><a href={`tel:${business.phoneIntl}`} className="font-bold hover:text-brand-red">Telepon {business.phoneDisplay}</a></li><li className="flex items-start gap-3"><MailIcon className="mt-0.5 size-5 shrink-0 text-brand-red" /><a href={`mailto:${business.email}`} className="font-bold hover:text-brand-red">{business.email}</a></li><li className="flex items-start gap-3"><ClockIcon className="mt-0.5 size-5 shrink-0 text-brand-red" /><div className="flex flex-col gap-1 text-muted-foreground">{business.hours.map((hours) => <span key={hours.day}>{hours.day}: {hours.time}</span>)}</div></li></ul><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild className="h-auto min-h-11 flex-1 bg-brand-red py-3 text-white hover:bg-brand-red/90"><a href={waLink(waGeneralMessage())} target="_blank" rel="noopener noreferrer"><WhatsAppIcon /> Chat WhatsApp</a></Button><Button asChild variant="outline" className="h-auto min-h-11 flex-1 py-3"><a href={business.googleMapsUrl} target="_blank" rel="noopener noreferrer"><MapPinIcon /> Buka Maps</a></Button></div></div></div></div></section>;
}
